# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbb4f3a3e4fff39afe9e17c193af5eed8e73980d9835b78c821edbfc4046e6a265622a2bbd662b5b5473eb6ef18441cacdde92e2a5ab5c1925e8f22f2d3da5b2

test:
  secret_key_base: 89e67162fba2637f8d5bde7f8bf2c7b143bbcd8bde728e7a2ada0363d4c2532a7a88647c02aa7dac2258e89dbefef3f91809790815a0214a1c3344134b782547

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
